/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as CitaRouteImport } from './routes/cita'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PresupuestoRouteImport } from './routes/presupuesto'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as TallerRouteImport } from './routes/taller'
import { Route as VenderMiCocheRouteImport } from './routes/vender-mi-coche'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as VehiculosIndexRouteImport } from './routes/vehiculos.index'
import { Route as VehiculosVehicleIdRouteImport } from './routes/vehiculos.$vehicleId'
import { Route as AdminCitasIndexRouteImport } from './routes/admin.citas.index'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin.leads.index'
import { Route as AdminVehiculosIndexRouteImport } from './routes/admin.vehiculos.index'
import { Route as AdminVehiculosNuevoRouteImport } from './routes/admin.vehiculos.nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CitaRoute = CitaRouteImport.update({
  id: '/cita',
  path: '/cita',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoRoute = PresupuestoRouteImport.update({
  id: '/presupuesto',
  path: '/presupuesto',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerRoute = TallerRouteImport.update({
  id: '/taller',
  path: '/taller',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderMiCocheRoute = VenderMiCocheRouteImport.update({
  id: '/vender-mi-coche',
  path: '/vender-mi-coche',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosIndexRoute = VehiculosIndexRouteImport.update({
  id: '/vehiculos/',
  path: '/vehiculos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosVehicleIdRoute = VehiculosVehicleIdRouteImport.update({
  id: '/vehiculos/$vehicleId',
  path: '/vehiculos/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCitasIndexRoute = AdminCitasIndexRouteImport.update({
  id: '/citas/',
  path: '/citas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiculosIndexRoute = AdminVehiculosIndexRouteImport.update({
  id: '/vehiculos/',
  path: '/vehiculos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiculosNuevoRoute = AdminVehiculosNuevoRouteImport.update({
  id: '/vehiculos/nuevo',
  path: '/vehiculos/nuevo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/cita': typeof CitaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/presupuesto': typeof PresupuestoRoute
  '/privacidad': typeof PrivacidadRoute
  '/taller': typeof TallerRoute
  '/vender-mi-coche': typeof VenderMiCocheRoute
  '/admin/login': typeof AdminLoginRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/vehiculos/$vehicleId': typeof VehiculosVehicleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/vehiculos/': typeof VehiculosIndexRoute
  '/admin/vehiculos/nuevo': typeof AdminVehiculosNuevoRoute
  '/admin/citas/': typeof AdminCitasIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/vehiculos/': typeof AdminVehiculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cita': typeof CitaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/presupuesto': typeof PresupuestoRoute
  '/privacidad': typeof PrivacidadRoute
  '/taller': typeof TallerRoute
  '/vender-mi-coche': typeof VenderMiCocheRoute
  '/admin/login': typeof AdminLoginRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/vehiculos/$vehicleId': typeof VehiculosVehicleIdRoute
  '/admin': typeof AdminIndexRoute
  '/servicios': typeof ServiciosIndexRoute
  '/vehiculos': typeof VehiculosIndexRoute
  '/admin/vehiculos/nuevo': typeof AdminVehiculosNuevoRoute
  '/admin/citas': typeof AdminCitasIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
  '/admin/vehiculos': typeof AdminVehiculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/cita': typeof CitaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/presupuesto': typeof PresupuestoRoute
  '/privacidad': typeof PrivacidadRoute
  '/taller': typeof TallerRoute
  '/vender-mi-coche': typeof VenderMiCocheRoute
  '/admin/login': typeof AdminLoginRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/vehiculos/$vehicleId': typeof VehiculosVehicleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/vehiculos/': typeof VehiculosIndexRoute
  '/admin/vehiculos/nuevo': typeof AdminVehiculosNuevoRoute
  '/admin/citas/': typeof AdminCitasIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/vehiculos/': typeof AdminVehiculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/admin'
    | '/aviso-legal'
    | '/cita'
    | '/contacto'
    | '/cookies'
    | '/faq'
    | '/presupuesto'
    | '/privacidad'
    | '/taller'
    | '/vender-mi-coche'
    | '/admin/login'
    | '/servicios/$slug'
    | '/vehiculos/$vehicleId'
    | '/admin/'
    | '/servicios/'
    | '/vehiculos/'
    | '/admin/vehiculos/nuevo'
    | '/admin/citas/'
    | '/admin/leads/'
    | '/admin/vehiculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/aviso-legal'
    | '/cita'
    | '/contacto'
    | '/cookies'
    | '/faq'
    | '/presupuesto'
    | '/privacidad'
    | '/taller'
    | '/vender-mi-coche'
    | '/admin/login'
    | '/servicios/$slug'
    | '/vehiculos/$vehicleId'
    | '/admin'
    | '/servicios'
    | '/vehiculos'
    | '/admin/vehiculos/nuevo'
    | '/admin/citas'
    | '/admin/leads'
    | '/admin/vehiculos'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/admin'
    | '/aviso-legal'
    | '/cita'
    | '/contacto'
    | '/cookies'
    | '/faq'
    | '/presupuesto'
    | '/privacidad'
    | '/taller'
    | '/vender-mi-coche'
    | '/admin/login'
    | '/servicios/$slug'
    | '/vehiculos/$vehicleId'
    | '/admin/'
    | '/servicios/'
    | '/vehiculos/'
    | '/admin/vehiculos/nuevo'
    | '/admin/citas/'
    | '/admin/leads/'
    | '/admin/vehiculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisoLegalRoute: typeof AvisoLegalRoute
  CitaRoute: typeof CitaRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  PresupuestoRoute: typeof PresupuestoRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TallerRoute: typeof TallerRoute
  VenderMiCocheRoute: typeof VenderMiCocheRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  VehiculosVehicleIdRoute: typeof VehiculosVehicleIdRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
  VehiculosIndexRoute: typeof VehiculosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cita': {
      id: '/cita'
      path: '/cita'
      fullPath: '/cita'
      preLoaderRoute: typeof CitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto': {
      id: '/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof PresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller': {
      id: '/taller'
      path: '/taller'
      fullPath: '/taller'
      preLoaderRoute: typeof TallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender-mi-coche': {
      id: '/vender-mi-coche'
      path: '/vender-mi-coche'
      fullPath: '/vender-mi-coche'
      preLoaderRoute: typeof VenderMiCocheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos/': {
      id: '/vehiculos/'
      path: '/vehiculos'
      fullPath: '/vehiculos/'
      preLoaderRoute: typeof VehiculosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos/$vehicleId': {
      id: '/vehiculos/$vehicleId'
      path: '/vehiculos/$vehicleId'
      fullPath: '/vehiculos/$vehicleId'
      preLoaderRoute: typeof VehiculosVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/citas/': {
      id: '/admin/citas/'
      path: '/citas'
      fullPath: '/admin/citas/'
      preLoaderRoute: typeof AdminCitasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehiculos/': {
      id: '/admin/vehiculos/'
      path: '/vehiculos'
      fullPath: '/admin/vehiculos/'
      preLoaderRoute: typeof AdminVehiculosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehiculos/nuevo': {
      id: '/admin/vehiculos/nuevo'
      path: '/vehiculos/nuevo'
      fullPath: '/admin/vehiculos/nuevo'
      preLoaderRoute: typeof AdminVehiculosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminVehiculosNuevoRoute: typeof AdminVehiculosNuevoRoute
  AdminCitasIndexRoute: typeof AdminCitasIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
  AdminVehiculosIndexRoute: typeof AdminVehiculosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminVehiculosNuevoRoute: AdminVehiculosNuevoRoute,
  AdminCitasIndexRoute: AdminCitasIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
  AdminVehiculosIndexRoute: AdminVehiculosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisoLegalRoute: AvisoLegalRoute,
  CitaRoute: CitaRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  PresupuestoRoute: PresupuestoRoute,
  PrivacidadRoute: PrivacidadRoute,
  TallerRoute: TallerRoute,
  VenderMiCocheRoute: VenderMiCocheRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  VehiculosVehicleIdRoute: VehiculosVehicleIdRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
  VehiculosIndexRoute: VehiculosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
