/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitaRouteImport } from './routes/cita'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as PresupuestoRouteImport } from './routes/presupuesto'
import { Route as TallerRouteImport } from './routes/taller'
import { Route as VenderMiCocheRouteImport } from './routes/vender-mi-coche'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as VehiculosIndexRouteImport } from './routes/vehiculos.index'
import { Route as VehiculosVehicleIdRouteImport } from './routes/vehiculos.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitaRoute = CitaRouteImport.update({
  id: '/cita',
  path: '/cita',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoRoute = PresupuestoRouteImport.update({
  id: '/presupuesto',
  path: '/presupuesto',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerRoute = TallerRouteImport.update({
  id: '/taller',
  path: '/taller',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderMiCocheRoute = VenderMiCocheRouteImport.update({
  id: '/vender-mi-coche',
  path: '/vender-mi-coche',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosIndexRoute = VehiculosIndexRouteImport.update({
  id: '/vehiculos/',
  path: '/vehiculos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculosVehicleIdRoute = VehiculosVehicleIdRouteImport.update({
  id: '/vehiculos/$vehicleId',
  path: '/vehiculos/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cita': typeof CitaRoute
  '/contacto': typeof ContactoRoute
  '/presupuesto': typeof PresupuestoRoute
  '/taller': typeof TallerRoute
  '/vender-mi-coche': typeof VenderMiCocheRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/vehiculos/$vehicleId': typeof VehiculosVehicleIdRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/vehiculos/': typeof VehiculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cita': typeof CitaRoute
  '/contacto': typeof ContactoRoute
  '/presupuesto': typeof PresupuestoRoute
  '/taller': typeof TallerRoute
  '/vender-mi-coche': typeof VenderMiCocheRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/vehiculos/$vehicleId': typeof VehiculosVehicleIdRoute
  '/servicios': typeof ServiciosIndexRoute
  '/vehiculos': typeof VehiculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cita': typeof CitaRoute
  '/contacto': typeof ContactoRoute
  '/presupuesto': typeof PresupuestoRoute
  '/taller': typeof TallerRoute
  '/vender-mi-coche': typeof VenderMiCocheRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/vehiculos/$vehicleId': typeof VehiculosVehicleIdRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/vehiculos/': typeof VehiculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cita'
    | '/contacto'
    | '/presupuesto'
    | '/taller'
    | '/vender-mi-coche'
    | '/servicios/$slug'
    | '/vehiculos/$vehicleId'
    | '/servicios/'
    | '/vehiculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cita'
    | '/contacto'
    | '/presupuesto'
    | '/taller'
    | '/vender-mi-coche'
    | '/servicios/$slug'
    | '/vehiculos/$vehicleId'
    | '/servicios'
    | '/vehiculos'
  id:
    | '__root__'
    | '/'
    | '/cita'
    | '/contacto'
    | '/presupuesto'
    | '/taller'
    | '/vender-mi-coche'
    | '/servicios/$slug'
    | '/vehiculos/$vehicleId'
    | '/servicios/'
    | '/vehiculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitaRoute: typeof CitaRoute
  ContactoRoute: typeof ContactoRoute
  PresupuestoRoute: typeof PresupuestoRoute
  TallerRoute: typeof TallerRoute
  VenderMiCocheRoute: typeof VenderMiCocheRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  VehiculosVehicleIdRoute: typeof VehiculosVehicleIdRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
  VehiculosIndexRoute: typeof VehiculosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cita': {
      id: '/cita'
      path: '/cita'
      fullPath: '/cita'
      preLoaderRoute: typeof CitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto': {
      id: '/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof PresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller': {
      id: '/taller'
      path: '/taller'
      fullPath: '/taller'
      preLoaderRoute: typeof TallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender-mi-coche': {
      id: '/vender-mi-coche'
      path: '/vender-mi-coche'
      fullPath: '/vender-mi-coche'
      preLoaderRoute: typeof VenderMiCocheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos/': {
      id: '/vehiculos/'
      path: '/vehiculos'
      fullPath: '/vehiculos/'
      preLoaderRoute: typeof VehiculosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculos/$vehicleId': {
      id: '/vehiculos/$vehicleId'
      path: '/vehiculos/$vehicleId'
      fullPath: '/vehiculos/$vehicleId'
      preLoaderRoute: typeof VehiculosVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitaRoute: CitaRoute,
  ContactoRoute: ContactoRoute,
  PresupuestoRoute: PresupuestoRoute,
  TallerRoute: TallerRoute,
  VenderMiCocheRoute: VenderMiCocheRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  VehiculosVehicleIdRoute: VehiculosVehicleIdRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
  VehiculosIndexRoute: VehiculosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
