/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandSlugRouteImport } from './routes/$brandSlug'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AireAcondicionadoSevillaRouteImport } from './routes/aire-acondicionado-sevilla'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as CambioAceiteSevillaRouteImport } from './routes/cambio-aceite-sevilla'
import { Route as CitaRouteImport } from './routes/cita'
import { Route as CochesBaratosSevillaRouteImport } from './routes/coches-baratos-sevilla'
import { Route as CochesKm0SevillaRouteImport } from './routes/coches-km0-sevilla'
import { Route as CochesOcasionSevillaRouteImport } from './routes/coches-ocasion-sevilla'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EmbragueSevillaRouteImport } from './routes/embrague-sevilla'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FrenosSevillaRouteImport } from './routes/frenos-sevilla'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PresupuestoRouteImport } from './routes/presupuesto'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as TallerRouteImport } from './routes/taller'
import { Route as TallerMecanicoSevillaRouteImport } from './routes/taller-mecanico-sevilla'
import { Route as TallerMultimarcaSevillaRouteImport } from './routes/taller-multimarca-sevilla'
import { Route as VenderMiCocheRouteImport } from './routes/vender-mi-coche'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAjustesRouteImport } from './routes/admin.ajustes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CochesSegundaManoSevillaIndexRouteImport } from './routes/coches-segunda-mano-sevilla.index'
import { Route as CochesVehicleSlugRouteImport } from './routes/coches.$vehicleSlug'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as AdminCitasIndexRouteImport } from './routes/admin.citas.index'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin.leads.index'
import { Route as AdminPresupuestosIndexRouteImport } from './routes/admin.presupuestos.index'
import { Route as AdminVehiculosIndexRouteImport } from './routes/admin.vehiculos.index'
import { Route as AdminVehiculosNuevoRouteImport } from './routes/admin.vehiculos.nuevo'
import { Route as AdminVehiculosEditarVehicleIdRouteImport } from './routes/admin.vehiculos.editar.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/$brandSlug',
  path: '/$brandSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AireAcondicionadoSevillaRoute =
  AireAcondicionadoSevillaRouteImport.update({
    id: '/aire-acondicionado-sevilla',
    path: '/aire-acondicionado-sevilla',
    getParentRoute: () => rootRouteImport,
  } as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CambioAceiteSevillaRoute = CambioAceiteSevillaRouteImport.update({
  id: '/cambio-aceite-sevilla',
  path: '/cambio-aceite-sevilla',
  getParentRoute: () => rootRouteImport,
} as any)
const CitaRoute = CitaRouteImport.update({
  id: '/cita',
  path: '/cita',
  getParentRoute: () => rootRouteImport,
} as any)
const CochesBaratosSevillaRoute = CochesBaratosSevillaRouteImport.update({
  id: '/coches-baratos-sevilla',
  path: '/coches-baratos-sevilla',
  getParentRoute: () => rootRouteImport,
} as any)
const CochesKm0SevillaRoute = CochesKm0SevillaRouteImport.update({
  id: '/coches-km0-sevilla',
  path: '/coches-km0-sevilla',
  getParentRoute: () => rootRouteImport,
} as any)
const CochesOcasionSevillaRoute = CochesOcasionSevillaRouteImport.update({
  id: '/coches-ocasion-sevilla',
  path: '/coches-ocasion-sevilla',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbragueSevillaRoute = EmbragueSevillaRouteImport.update({
  id: '/embrague-sevilla',
  path: '/embrague-sevilla',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FrenosSevillaRoute = FrenosSevillaRouteImport.update({
  id: '/frenos-sevilla',
  path: '/frenos-sevilla',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoRoute = PresupuestoRouteImport.update({
  id: '/presupuesto',
  path: '/presupuesto',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerRoute = TallerRouteImport.update({
  id: '/taller',
  path: '/taller',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerMecanicoSevillaRoute = TallerMecanicoSevillaRouteImport.update({
  id: '/taller-mecanico-sevilla',
  path: '/taller-mecanico-sevilla',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerMultimarcaSevillaRoute = TallerMultimarcaSevillaRouteImport.update({
  id: '/taller-multimarca-sevilla',
  path: '/taller-multimarca-sevilla',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderMiCocheRoute = VenderMiCocheRouteImport.update({
  id: '/vender-mi-coche',
  path: '/vender-mi-coche',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAjustesRoute = AdminAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const CochesSegundaManoSevillaIndexRoute =
  CochesSegundaManoSevillaIndexRouteImport.update({
    id: '/coches-segunda-mano-sevilla/',
    path: '/coches-segunda-mano-sevilla/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CochesVehicleSlugRoute = CochesVehicleSlugRouteImport.update({
  id: '/coches/$vehicleSlug',
  path: '/coches/$vehicleSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCitasIndexRoute = AdminCitasIndexRouteImport.update({
  id: '/citas/',
  path: '/citas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresupuestosIndexRoute = AdminPresupuestosIndexRouteImport.update({
  id: '/presupuestos/',
  path: '/presupuestos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiculosIndexRoute = AdminVehiculosIndexRouteImport.update({
  id: '/vehiculos/',
  path: '/vehiculos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiculosNuevoRoute = AdminVehiculosNuevoRouteImport.update({
  id: '/vehiculos/nuevo',
  path: '/vehiculos/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiculosEditarVehicleIdRoute =
  AdminVehiculosEditarVehicleIdRouteImport.update({
    id: '/vehiculos/editar/$vehicleId',
    path: '/vehiculos/editar/$vehicleId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$brandSlug': typeof BrandSlugRoute
  '/acceso': typeof AccesoRoute
  '/admin': typeof AdminRouteWithChildren
  '/aire-acondicionado-sevilla': typeof AireAcondicionadoSevillaRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cambio-aceite-sevilla': typeof CambioAceiteSevillaRoute
  '/cita': typeof CitaRoute
  '/coches-baratos-sevilla': typeof CochesBaratosSevillaRoute
  '/coches-km0-sevilla': typeof CochesKm0SevillaRoute
  '/coches-ocasion-sevilla': typeof CochesOcasionSevillaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/embrague-sevilla': typeof EmbragueSevillaRoute
  '/faq': typeof FaqRoute
  '/frenos-sevilla': typeof FrenosSevillaRoute
  '/historial': typeof HistorialRoute
  '/nosotros': typeof NosotrosRoute
  '/presupuesto': typeof PresupuestoRoute
  '/privacidad': typeof PrivacidadRoute
  '/taller': typeof TallerRoute
  '/taller-mecanico-sevilla': typeof TallerMecanicoSevillaRoute
  '/taller-multimarca-sevilla': typeof TallerMultimarcaSevillaRoute
  '/vender-mi-coche': typeof VenderMiCocheRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/login': typeof AdminLoginRoute
  '/coches/$vehicleSlug': typeof CochesVehicleSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/coches-segunda-mano-sevilla/': typeof CochesSegundaManoSevillaIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/admin/vehiculos/nuevo': typeof AdminVehiculosNuevoRoute
  '/admin/citas/': typeof AdminCitasIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/presupuestos/': typeof AdminPresupuestosIndexRoute
  '/admin/vehiculos/': typeof AdminVehiculosIndexRoute
  '/admin/vehiculos/editar/$vehicleId': typeof AdminVehiculosEditarVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$brandSlug': typeof BrandSlugRoute
  '/acceso': typeof AccesoRoute
  '/aire-acondicionado-sevilla': typeof AireAcondicionadoSevillaRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cambio-aceite-sevilla': typeof CambioAceiteSevillaRoute
  '/cita': typeof CitaRoute
  '/coches-baratos-sevilla': typeof CochesBaratosSevillaRoute
  '/coches-km0-sevilla': typeof CochesKm0SevillaRoute
  '/coches-ocasion-sevilla': typeof CochesOcasionSevillaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/embrague-sevilla': typeof EmbragueSevillaRoute
  '/faq': typeof FaqRoute
  '/frenos-sevilla': typeof FrenosSevillaRoute
  '/historial': typeof HistorialRoute
  '/nosotros': typeof NosotrosRoute
  '/presupuesto': typeof PresupuestoRoute
  '/privacidad': typeof PrivacidadRoute
  '/taller': typeof TallerRoute
  '/taller-mecanico-sevilla': typeof TallerMecanicoSevillaRoute
  '/taller-multimarca-sevilla': typeof TallerMultimarcaSevillaRoute
  '/vender-mi-coche': typeof VenderMiCocheRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/login': typeof AdminLoginRoute
  '/coches/$vehicleSlug': typeof CochesVehicleSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/coches-segunda-mano-sevilla': typeof CochesSegundaManoSevillaIndexRoute
  '/servicios': typeof ServiciosIndexRoute
  '/admin/vehiculos/nuevo': typeof AdminVehiculosNuevoRoute
  '/admin/citas': typeof AdminCitasIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
  '/admin/presupuestos': typeof AdminPresupuestosIndexRoute
  '/admin/vehiculos': typeof AdminVehiculosIndexRoute
  '/admin/vehiculos/editar/$vehicleId': typeof AdminVehiculosEditarVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$brandSlug': typeof BrandSlugRoute
  '/acceso': typeof AccesoRoute
  '/admin': typeof AdminRouteWithChildren
  '/aire-acondicionado-sevilla': typeof AireAcondicionadoSevillaRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cambio-aceite-sevilla': typeof CambioAceiteSevillaRoute
  '/cita': typeof CitaRoute
  '/coches-baratos-sevilla': typeof CochesBaratosSevillaRoute
  '/coches-km0-sevilla': typeof CochesKm0SevillaRoute
  '/coches-ocasion-sevilla': typeof CochesOcasionSevillaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/embrague-sevilla': typeof EmbragueSevillaRoute
  '/faq': typeof FaqRoute
  '/frenos-sevilla': typeof FrenosSevillaRoute
  '/historial': typeof HistorialRoute
  '/nosotros': typeof NosotrosRoute
  '/presupuesto': typeof PresupuestoRoute
  '/privacidad': typeof PrivacidadRoute
  '/taller': typeof TallerRoute
  '/taller-mecanico-sevilla': typeof TallerMecanicoSevillaRoute
  '/taller-multimarca-sevilla': typeof TallerMultimarcaSevillaRoute
  '/vender-mi-coche': typeof VenderMiCocheRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/login': typeof AdminLoginRoute
  '/coches/$vehicleSlug': typeof CochesVehicleSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/coches-segunda-mano-sevilla/': typeof CochesSegundaManoSevillaIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/admin/vehiculos/nuevo': typeof AdminVehiculosNuevoRoute
  '/admin/citas/': typeof AdminCitasIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/presupuestos/': typeof AdminPresupuestosIndexRoute
  '/admin/vehiculos/': typeof AdminVehiculosIndexRoute
  '/admin/vehiculos/editar/$vehicleId': typeof AdminVehiculosEditarVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$brandSlug'
    | '/acceso'
    | '/admin'
    | '/aire-acondicionado-sevilla'
    | '/aviso-legal'
    | '/cambio-aceite-sevilla'
    | '/cita'
    | '/coches-baratos-sevilla'
    | '/coches-km0-sevilla'
    | '/coches-ocasion-sevilla'
    | '/contacto'
    | '/cookies'
    | '/embrague-sevilla'
    | '/faq'
    | '/frenos-sevilla'
    | '/historial'
    | '/nosotros'
    | '/presupuesto'
    | '/privacidad'
    | '/taller'
    | '/taller-mecanico-sevilla'
    | '/taller-multimarca-sevilla'
    | '/vender-mi-coche'
    | '/admin/ajustes'
    | '/admin/login'
    | '/coches/$vehicleSlug'
    | '/servicios/$slug'
    | '/admin/'
    | '/coches-segunda-mano-sevilla/'
    | '/servicios/'
    | '/admin/vehiculos/nuevo'
    | '/admin/citas/'
    | '/admin/leads/'
    | '/admin/presupuestos/'
    | '/admin/vehiculos/'
    | '/admin/vehiculos/editar/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$brandSlug'
    | '/acceso'
    | '/aire-acondicionado-sevilla'
    | '/aviso-legal'
    | '/cambio-aceite-sevilla'
    | '/cita'
    | '/coches-baratos-sevilla'
    | '/coches-km0-sevilla'
    | '/coches-ocasion-sevilla'
    | '/contacto'
    | '/cookies'
    | '/embrague-sevilla'
    | '/faq'
    | '/frenos-sevilla'
    | '/historial'
    | '/nosotros'
    | '/presupuesto'
    | '/privacidad'
    | '/taller'
    | '/taller-mecanico-sevilla'
    | '/taller-multimarca-sevilla'
    | '/vender-mi-coche'
    | '/admin/ajustes'
    | '/admin/login'
    | '/coches/$vehicleSlug'
    | '/servicios/$slug'
    | '/admin'
    | '/coches-segunda-mano-sevilla'
    | '/servicios'
    | '/admin/vehiculos/nuevo'
    | '/admin/citas'
    | '/admin/leads'
    | '/admin/presupuestos'
    | '/admin/vehiculos'
    | '/admin/vehiculos/editar/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/$brandSlug'
    | '/acceso'
    | '/admin'
    | '/aire-acondicionado-sevilla'
    | '/aviso-legal'
    | '/cambio-aceite-sevilla'
    | '/cita'
    | '/coches-baratos-sevilla'
    | '/coches-km0-sevilla'
    | '/coches-ocasion-sevilla'
    | '/contacto'
    | '/cookies'
    | '/embrague-sevilla'
    | '/faq'
    | '/frenos-sevilla'
    | '/historial'
    | '/nosotros'
    | '/presupuesto'
    | '/privacidad'
    | '/taller'
    | '/taller-mecanico-sevilla'
    | '/taller-multimarca-sevilla'
    | '/vender-mi-coche'
    | '/admin/ajustes'
    | '/admin/login'
    | '/coches/$vehicleSlug'
    | '/servicios/$slug'
    | '/admin/'
    | '/coches-segunda-mano-sevilla/'
    | '/servicios/'
    | '/admin/vehiculos/nuevo'
    | '/admin/citas/'
    | '/admin/leads/'
    | '/admin/presupuestos/'
    | '/admin/vehiculos/'
    | '/admin/vehiculos/editar/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandSlugRoute: typeof BrandSlugRoute
  AccesoRoute: typeof AccesoRoute
  AdminRoute: typeof AdminRouteWithChildren
  AireAcondicionadoSevillaRoute: typeof AireAcondicionadoSevillaRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  CambioAceiteSevillaRoute: typeof CambioAceiteSevillaRoute
  CitaRoute: typeof CitaRoute
  CochesBaratosSevillaRoute: typeof CochesBaratosSevillaRoute
  CochesKm0SevillaRoute: typeof CochesKm0SevillaRoute
  CochesOcasionSevillaRoute: typeof CochesOcasionSevillaRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  EmbragueSevillaRoute: typeof EmbragueSevillaRoute
  FaqRoute: typeof FaqRoute
  FrenosSevillaRoute: typeof FrenosSevillaRoute
  HistorialRoute: typeof HistorialRoute
  NosotrosRoute: typeof NosotrosRoute
  PresupuestoRoute: typeof PresupuestoRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TallerRoute: typeof TallerRoute
  TallerMecanicoSevillaRoute: typeof TallerMecanicoSevillaRoute
  TallerMultimarcaSevillaRoute: typeof TallerMultimarcaSevillaRoute
  VenderMiCocheRoute: typeof VenderMiCocheRoute
  CochesVehicleSlugRoute: typeof CochesVehicleSlugRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  CochesSegundaManoSevillaIndexRoute: typeof CochesSegundaManoSevillaIndexRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$brandSlug': {
      id: '/$brandSlug'
      path: '/$brandSlug'
      fullPath: '/$brandSlug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aire-acondicionado-sevilla': {
      id: '/aire-acondicionado-sevilla'
      path: '/aire-acondicionado-sevilla'
      fullPath: '/aire-acondicionado-sevilla'
      preLoaderRoute: typeof AireAcondicionadoSevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambio-aceite-sevilla': {
      id: '/cambio-aceite-sevilla'
      path: '/cambio-aceite-sevilla'
      fullPath: '/cambio-aceite-sevilla'
      preLoaderRoute: typeof CambioAceiteSevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cita': {
      id: '/cita'
      path: '/cita'
      fullPath: '/cita'
      preLoaderRoute: typeof CitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coches-baratos-sevilla': {
      id: '/coches-baratos-sevilla'
      path: '/coches-baratos-sevilla'
      fullPath: '/coches-baratos-sevilla'
      preLoaderRoute: typeof CochesBaratosSevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coches-km0-sevilla': {
      id: '/coches-km0-sevilla'
      path: '/coches-km0-sevilla'
      fullPath: '/coches-km0-sevilla'
      preLoaderRoute: typeof CochesKm0SevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coches-ocasion-sevilla': {
      id: '/coches-ocasion-sevilla'
      path: '/coches-ocasion-sevilla'
      fullPath: '/coches-ocasion-sevilla'
      preLoaderRoute: typeof CochesOcasionSevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embrague-sevilla': {
      id: '/embrague-sevilla'
      path: '/embrague-sevilla'
      fullPath: '/embrague-sevilla'
      preLoaderRoute: typeof EmbragueSevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frenos-sevilla': {
      id: '/frenos-sevilla'
      path: '/frenos-sevilla'
      fullPath: '/frenos-sevilla'
      preLoaderRoute: typeof FrenosSevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto': {
      id: '/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof PresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller': {
      id: '/taller'
      path: '/taller'
      fullPath: '/taller'
      preLoaderRoute: typeof TallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller-mecanico-sevilla': {
      id: '/taller-mecanico-sevilla'
      path: '/taller-mecanico-sevilla'
      fullPath: '/taller-mecanico-sevilla'
      preLoaderRoute: typeof TallerMecanicoSevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller-multimarca-sevilla': {
      id: '/taller-multimarca-sevilla'
      path: '/taller-multimarca-sevilla'
      fullPath: '/taller-multimarca-sevilla'
      preLoaderRoute: typeof TallerMultimarcaSevillaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender-mi-coche': {
      id: '/vender-mi-coche'
      path: '/vender-mi-coche'
      fullPath: '/vender-mi-coche'
      preLoaderRoute: typeof VenderMiCocheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ajustes': {
      id: '/admin/ajustes'
      path: '/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AdminAjustesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/coches-segunda-mano-sevilla/': {
      id: '/coches-segunda-mano-sevilla/'
      path: '/coches-segunda-mano-sevilla'
      fullPath: '/coches-segunda-mano-sevilla/'
      preLoaderRoute: typeof CochesSegundaManoSevillaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coches/$vehicleSlug': {
      id: '/coches/$vehicleSlug'
      path: '/coches/$vehicleSlug'
      fullPath: '/coches/$vehicleSlug'
      preLoaderRoute: typeof CochesVehicleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/citas/': {
      id: '/admin/citas/'
      path: '/citas'
      fullPath: '/admin/citas/'
      preLoaderRoute: typeof AdminCitasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/presupuestos/': {
      id: '/admin/presupuestos/'
      path: '/presupuestos'
      fullPath: '/admin/presupuestos/'
      preLoaderRoute: typeof AdminPresupuestosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehiculos/': {
      id: '/admin/vehiculos/'
      path: '/vehiculos'
      fullPath: '/admin/vehiculos/'
      preLoaderRoute: typeof AdminVehiculosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehiculos/nuevo': {
      id: '/admin/vehiculos/nuevo'
      path: '/vehiculos/nuevo'
      fullPath: '/admin/vehiculos/nuevo'
      preLoaderRoute: typeof AdminVehiculosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehiculos/editar/$vehicleId': {
      id: '/admin/vehiculos/editar/$vehicleId'
      path: '/vehiculos/editar/$vehicleId'
      fullPath: '/admin/vehiculos/editar/$vehicleId'
      preLoaderRoute: typeof AdminVehiculosEditarVehicleIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAjustesRoute: typeof AdminAjustesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminVehiculosNuevoRoute: typeof AdminVehiculosNuevoRoute
  AdminCitasIndexRoute: typeof AdminCitasIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
  AdminPresupuestosIndexRoute: typeof AdminPresupuestosIndexRoute
  AdminVehiculosIndexRoute: typeof AdminVehiculosIndexRoute
  AdminVehiculosEditarVehicleIdRoute: typeof AdminVehiculosEditarVehicleIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAjustesRoute: AdminAjustesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminVehiculosNuevoRoute: AdminVehiculosNuevoRoute,
  AdminCitasIndexRoute: AdminCitasIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
  AdminPresupuestosIndexRoute: AdminPresupuestosIndexRoute,
  AdminVehiculosIndexRoute: AdminVehiculosIndexRoute,
  AdminVehiculosEditarVehicleIdRoute: AdminVehiculosEditarVehicleIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandSlugRoute: BrandSlugRoute,
  AccesoRoute: AccesoRoute,
  AdminRoute: AdminRouteWithChildren,
  AireAcondicionadoSevillaRoute: AireAcondicionadoSevillaRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  CambioAceiteSevillaRoute: CambioAceiteSevillaRoute,
  CitaRoute: CitaRoute,
  CochesBaratosSevillaRoute: CochesBaratosSevillaRoute,
  CochesKm0SevillaRoute: CochesKm0SevillaRoute,
  CochesOcasionSevillaRoute: CochesOcasionSevillaRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  EmbragueSevillaRoute: EmbragueSevillaRoute,
  FaqRoute: FaqRoute,
  FrenosSevillaRoute: FrenosSevillaRoute,
  HistorialRoute: HistorialRoute,
  NosotrosRoute: NosotrosRoute,
  PresupuestoRoute: PresupuestoRoute,
  PrivacidadRoute: PrivacidadRoute,
  TallerRoute: TallerRoute,
  TallerMecanicoSevillaRoute: TallerMecanicoSevillaRoute,
  TallerMultimarcaSevillaRoute: TallerMultimarcaSevillaRoute,
  VenderMiCocheRoute: VenderMiCocheRoute,
  CochesVehicleSlugRoute: CochesVehicleSlugRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  CochesSegundaManoSevillaIndexRoute: CochesSegundaManoSevillaIndexRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
